name: smart_home
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  either_dart: ^1.0.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  bloc_concurrency: ^0.2.3
  stream_transform: ^2.1.0
  get_it: ^7.6.6
  flutter_bloc: ^8.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/onboarding/1.png
    - assets/onboarding/2.png
    - assets/onboarding/3.png
    - assets/onboarding/4.png
    - assets/logo.png
    - assets/home_logo.png
    - assets/battery_bg.png

  uses-material-design: true
